import { AktivitetsKort } from "./types";

export const initialKort: AktivitetsKort[] = [
  // --- Forslag ---
  {
    id: "1",
    kolonne: "forslag",
    type: "Stilling fra Nav",
    title: "Barnehageassistent",
    dateRange: "1. aug – 1. aug 2026",
    tags: ["ulest", "avtalt-med-nav"],
    hasBlueDot: true,
  },
  {
    id: "2",
    kolonne: "forslag",
    type: "Møte med Nav",
    title: "Møte om oppfølging",
    dateRange: "15. jul – 15. jul 2026",
    tags: ["ulest"],
    hasBlueDot: true,
  },
  // --- Planlegger ---
  {
    id: "3",
    kolonne: "planlegger",
    type: "Jobbsøking",
    title: "Søke på 5 stillinger denne uken",
    dateRange: "21. jun – 27. jun 2026",
    extraLine: "Antall søknader i uken: 5",
    tags: ["sendt-soknad"],
  },
  {
    id: "4",
    kolonne: "planlegger",
    type: "Stilling",
    title: "Lærer",
    dateRange: "20. sep 2026",
    startDato: "2026-09-20",
    tags: ["sendt-soknad"],
  },
  {
    id: "5",
    kolonne: "planlegger",
    type: "Jobbrettet egenaktivitet",
    title: "Oppdatere CV og LinkedIn-profil",
    tags: [],
  },
  // --- Gjennomfører ---
  {
    id: "6",
    kolonne: "gjennomforer",
    type: "Tiltak gjennom Nav",
    title: "Pedagogikk og barneutvikling",
    dateRange: "1. sep – 30. nov 2026",
    startDato: "2026-09-01",
    sluttDato: "2026-11-30",
    tags: ["fatt-plass", "avtalt-med-nav"],
  },
  {
    id: "7",
    kolonne: "gjennomforer",
    type: "Stilling",
    title: "Bartender",
    dateRange: "4. sep 2026",
    startDato: "2026-09-04",
    tags: ["skal-pa-intervju"],
  },
  {
    id: "8",
    kolonne: "gjennomforer",
    type: "Behandling",
    title: "Oppfølging hos behandler",
    dateRange: "5. jul – 5. aug 2026",
    tags: ["venter-pa-kontakt"],
  },
  {
    id: "9",
    kolonne: "gjennomforer",
    type: "Jobb jeg har nå",
    title: "Renholder",
    extraLine: "Heltid, fast stilling",
    tags: ["avtalt-med-nav"],
  },
  // --- Fullført ---
  {
    id: "10",
    kolonne: "fullfort",
    type: "Stilling",
    title: "Assistent på SFO",
    dateRange: "1. mar – 1. mar 2026",
    tags: ["fatt-jobben"],
  },
  {
    id: "11",
    kolonne: "fullfort",
    type: "Jobbsøking",
    title: "Søke på 3 stillinger",
    dateRange: "1. jun – 7. jun 2026",
    extraLine: "Antall søknader i uken: 3",
    tags: ["cv-er-delt"],
  },
  {
    id: "12",
    kolonne: "fullfort",
    type: "Samtalereferat",
    title: "Oppfølgingssamtale",
    dateRange: "10. jun 2026",
    tags: [],
    samtalereferatData: {
      dato: "10. jun 2026",
      moteform: "Telefonmøte",
      referatTekst:
        "Vi hadde en god samtale om veien videre. Motivert for å søke stillinger innenfor ditt fagfelt.\n\nVi avtalte at du skal sende inn en søknad i løpet av neste uke.\n\nDu ønsker også bistand til å oppdatere CV-en din.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
      erReferatPublisert: true,
    },
  },
  {
    id: "15",
    kolonne: "gjennomforer",
    type: "Samtalereferat",
    title: "Statusmøte",
    dateRange: "5. aug 2026",
    tags: [],
    samtalereferatData: {
      dato: "5. aug 2026",
      moteform: "Oppmøte",
      referatTekst: "Kort statusmøte. Vi gikk gjennom fremdrift og avtalte neste steg.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n\nExcepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
      erReferatPublisert: true,
    },
  },
  // --- Avbrutt ---
  {
    id: "13",
    kolonne: "avbrutt",
    type: "Møte med Nav",
    title: "Avklaringssamtale",
    dateRange: "20. mai – 20. mai 2026",
    tags: [],
  },
  {
    id: "14",
    kolonne: "avbrutt",
    type: "Arbeidstrening",
    title: "Arbeidstrening",
    dateRange: "1. apr – 30. apr 2026",
    tags: [],
  },
];
