import { AktivitetsKort } from "./types";

export const initialKort: AktivitetsKort[] = [
  {
    id: "1",
    kolonne: "forslag",
    type: "MØTE MED NAV",
    title: "Møte om oppfølging",
    subtitle: "NAV Grünerløkka",
    dateRange: "15. jul – 15. jul 2026",
    tags: ["ulest", "avtalt-med-nav"],
    hasBlueDot: true,
  },
  {
    id: "2",
    kolonne: "forslag",
    type: "STILLING",
    title: "Barnehageassistent",
    subtitle: "Trollskogen barnehage",
    dateRange: "1. aug – 1. aug 2026",
    tags: ["avtalt-med-nav"],
  },
  {
    id: "3",
    kolonne: "planlegger",
    type: "JOBBSØKING",
    title: "Søke på 5 stillinger denne uken",
    dateRange: "21. jun – 27. jun 2026",
    extraLine: "Antall søknader i uken: 5",
    tags: ["ikke-ferdig"],
  },
  {
    id: "4",
    kolonne: "planlegger",
    type: "STILLING",
    title: "Lærer på Trollskogen skole",
    subtitle: "Trollskogen skole · Grorud",
    dateRange: "15. aug – 15. aug 2026",
    tags: ["sendt-soknad"],
  },
  {
    id: "5",
    kolonne: "gjennomforer",
    type: "KURS",
    title: "Pedagogikk og barneutvikling",
    subtitle: "Høgskolen i Oslo",
    dateRange: "1. sep – 30. nov 2026",
    tags: ["deltar", "avtalt-med-nav"],
  },
  {
    id: "6",
    kolonne: "gjennomforer",
    type: "STILLING",
    title: "Bartender på Kulturhuset",
    subtitle: "Kulturhuset · Sentrum",
    dateRange: "10. jul – 10. jul 2026",
    tags: ["skal-pa-intervju"],
  },
  {
    id: "7",
    kolonne: "gjennomforer",
    type: "BEHANDLING",
    title: "Oppfølging hos fysioterapeut",
    dateRange: "5. jul – 5. aug 2026",
    tags: ["venter-svar"],
  },
  {
    id: "8",
    kolonne: "fullfort",
    type: "STILLING",
    title: "Assistent på SFO",
    subtitle: "Nydalen skole",
    dateRange: "1. mar – 1. mar 2026",
    tags: ["fatt-jobbtilbud"],
  },
  {
    id: "9",
    kolonne: "fullfort",
    type: "JOBBSØKING",
    title: "Søke på 3 stillinger",
    dateRange: "1. jun – 7. jun 2026",
    extraLine: "Antall søknader i uken: 3",
    tags: ["cv-er-delt"],
  },
  {
    id: "10",
    kolonne: "avbrutt",
    type: "MØTE MED NAV",
    title: "Avklaringssamtale",
    subtitle: "NAV Sagene",
    dateRange: "20. mai – 20. mai 2026",
    tags: [],
  },
];
