import { AktivitetsKort } from "./types";

export const initialKort: AktivitetsKort[] = [
  // --- Forslag ---
  {
    id: "1",
    kolonne: "forslag",
    type: "Møte med Nav",
    title: "Oppfølgingsmøte om yrkesvalg",
    dateRange: "15. jul – 15. jul 2026",
    tags: ["ulest"],
    hasBlueDot: true,
    moteform: "Oppmøte",
    varighet: "30 minutter",
    hensikt: "Snakke om veien tilbake til jobb som elektriker.",
    forberedelser: "Tenk gjennom hva du trenger av bistand for å komme i gang igjen.",
  },
  // --- Planlegger ---
  {
    id: "2",
    kolonne: "planlegger",
    type: "Jobbrettet egenaktivitet",
    title: "Oppdatere CV og LinkedIn-profil",
    tags: [],
    mal: "Ha en oppdatert CV klar til bruk i søknader som elektriker.",
    huskeliste: "Legg til fagbrev og relevant erfaring, sjekk kontaktinfo.",
    beskrivelse: "Sette av tid til å gå gjennom og oppdatere CV og profil rettet mot elektrikerbransjen.",
  },
  {
    id: "3",
    kolonne: "planlegger",
    type: "Jobbsøking",
    title: "Søke elektrikerstillinger",
    dateRange: "21. jun – 27. jun 2026",
    extraLine: "Antall søknader i uken: 5",
    tags: ["sendt-soknad"],
  },
  // --- Gjennomfører ---
  {
    id: "4",
    kolonne: "gjennomforer",
    type: "Behandling",
    title: "Oppfølging hos behandler",
    dateRange: "5. jul – 5. aug 2026",
    tags: ["venter-pa-kontakt"],
    behandlingstype: "Fysioterapi",
    behandlingssted: "Behandler",
    mal: "Redusere smerter og bedre bevegelighet slik at du kan stå i arbeid som elektriker.",
    oppfolgingFraNav: "Nav følger opp etter endt behandling.",
  },
  {
    id: "5",
    kolonne: "gjennomforer",
    type: "Tiltak gjennom Nav",
    title: "Oppdateringskurs for elektrikere og telekommunikasjonsmontører",
    dateRange: "1. sep – 30. nov 2026",
    startDato: "2026-09-01",
    sluttDato: "2026-11-30",
    tags: ["fatt-plass", "avtalt-med-nav"],
    arrangor: "Kursholder",
    deltakelseProsent: "100 %",
    dagerPerUke: "5",
    beskrivelse: "Oppdateringskurs for å friske opp fagkunnskap og komme tilbake i jobb som elektriker.",
  },
  // --- Fullført ---
  {
    id: "10",
    kolonne: "fullfort",
    type: "Stilling",
    title: "Assistent på SFO",
    dateRange: "1. mar – 1. mar 2026",
    tags: ["fatt-jobben"],
    arbeidsgiver: "Skole",
    arbeidssted: "Stavanger",
    beskrivelse: "Fikk tilbud om stilling som assistent på SFO.",
  },
  {
    id: "11",
    kolonne: "fullfort",
    type: "Jobbsøking",
    title: "Søke på 3 stillinger",
    dateRange: "1. jun – 7. jun 2026",
    extraLine: "Antall søknader i uken: 3",
    tags: ["cv-er-delt"],
  },
  {
    id: "12",
    kolonne: "fullfort",
    type: "Samtalereferat",
    title: "Oppfølgingssamtale",
    dateRange: "10. jun 2026",
    tags: [],
    samtalereferatData: {
      dato: "10. jun 2026",
      moteform: "Telefonmøte",
      referatTekst:
        "Vi hadde en god samtale om veien videre. Motivert for å søke stillinger innenfor ditt fagfelt.\n\nVi avtalte at du skal sende inn en søknad i løpet av neste uke.\n\nDu ønsker også bistand til å oppdatere CV-en din.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
      erReferatPublisert: true,
    },
  },
  // --- Avbrutt ---
  {
    id: "13",
    kolonne: "avbrutt",
    type: "Møte med Nav",
    title: "Avklaringssamtale",
    dateRange: "20. mai – 20. mai 2026",
    tags: [],
    moteform: "Telefonmøte",
    varighet: "15 minutter",
    hensikt: "Avklare videre oppfølging.",
  },
  {
    id: "14",
    kolonne: "avbrutt",
    type: "Arbeidstrening",
    title: "Arbeidstrening",
    dateRange: "1. apr – 30. apr 2026",
    tags: [],
    beskrivelse: "Arbeidstrening hos ekstern arbeidsgiver.",
    detaljRader: [
      { label: "Arrangør", verdi: "Tiltaksarrangør" },
      { label: "Stillingsprosent", verdi: "50 %" },
    ],
  },
];
